"""
Daily morning brief — TZ-aware per-user email digest.

What lands in each user's inbox at their configured local hour:

  1. Overnight     — God Mode runs (campaign_runs since last brief)
                     + sequence sends, replies, hot leads in last 24h
  2. Today's plan  — open tasks due today + hot leads needing follow-up
                     + stuck deals (>14d in same stage)
  3. Replies awaiting action — recent email replies tagged with sentiment
  4. AI insight    — single highest-value observation, generated by
                     Sonnet from the data above (~$0.005 per user / day)
  5. Weekly stats  — sends, opens, replies, calls vs prior 7 days
  6. Footer        — manage settings + snooze + unsubscribe

The cron tick (in app/main.py lifespan) iterates active users and
calls send_brief(user, db) when local time crosses brief_hour and we
haven't sent today.
"""
from __future__ import annotations
import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Optional
from zoneinfo import ZoneInfo

import httpx
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models import (
    User, Company, Contact, Deal, Activity, Task, GeneratedEmail,
    Campaign, CampaignRun,
)

log = logging.getLogger("bmp.morning_brief")


# ============================================================
# Data shape
# ============================================================

@dataclass
class BriefData:
    user: dict = field(default_factory=dict)
    overnight: dict = field(default_factory=dict)
    today_priorities: dict = field(default_factory=dict)
    replies_awaiting: list = field(default_factory=list)
    weekly_stats: dict = field(default_factory=dict)
    ai_insight: str = ""


# ============================================================
# Builder — gathers the data
# ============================================================

async def build_brief(db: AsyncSession, user: User) -> BriefData:
    """Collect everything that lands in the email body. Pure data — no
    rendering, no email send. Safe to call from anywhere (preview UI,
    test endpoint, cron loop)."""
    now_utc = datetime.now(timezone.utc)
    yesterday_utc = now_utc - timedelta(days=1)
    week_ago = now_utc - timedelta(days=7)
    two_weeks_ago = now_utc - timedelta(days=14)

    brief = BriefData(user={
        "id": user.id,
        "first_name": user.first_name or "",
        "email": user.email,
    })

    # ---- Overnight (last ~24h or since last brief, whichever is shorter) ----
    since = user.last_brief_sent_at or yesterday_utc
    if since.tzinfo is None:
        since = since.replace(tzinfo=timezone.utc)
    if (now_utc - since) > timedelta(days=2):
        since = yesterday_utc  # cap at 24h on first ever brief

    overnight = {}

    # God Mode runs for campaigns this user owns
    user_campaign_ids = (await db.execute(
        select(Campaign.id).where(Campaign.created_by == user.id)
    )).scalars().all()
    if user_campaign_ids:
        runs = (await db.execute(
            select(CampaignRun)
            .where(
                CampaignRun.campaign_id.in_(user_campaign_ids),
                CampaignRun.started_at >= since,
            )
            .order_by(CampaignRun.started_at.desc())
        )).scalars().all()
        overnight["campaign_ticks"] = len(runs)
        overnight["contacts_enrolled_overnight"] = sum(r.contacts_enrolled or 0 for r in runs)
    else:
        overnight["campaign_ticks"] = 0
        overnight["contacts_enrolled_overnight"] = 0

    # Sequence sends authored by this user since the cutoff.
    # POST-CUTOVER: read from Activity (activity_type='email_sent')
    # rather than GeneratedEmail. The new engine writes Activity rows
    # on every send (via EmailChannel dual-write), and the legacy
    # send_routes path also writes Activity. So Activity is the single
    # source of truth for "emails sent" counts; querying GeneratedEmail
    # alone undercounts every new-engine send by 100%.
    sends_q = (
        select(func.count(Activity.id))
        .where(
            Activity.activity_type == "email_sent",
            Activity.created_at >= since,
        )
    )
    if user.role not in ("admin", "super_admin"):
        sends_q = sends_q.where(Activity.user_id == user.id)
    sends_count = (await db.execute(sends_q)).scalar() or 0
    overnight["sends_overnight"] = int(sends_count)

    # Replies on companies assigned to this user (or any if admin)
    replies_q = (
        select(func.count(Activity.id))
        .where(
            Activity.activity_type == "email_replied",
            Activity.created_at >= since,
        )
    )
    if user.role not in ("admin", "super_admin"):
        replies_q = replies_q.join(Company, Activity.company_id == Company.id).where(
            Company.assigned_to == user.id
        )
    overnight["replies_overnight"] = int((await db.execute(replies_q)).scalar() or 0)

    # Hot leads (lead_score >= 60) for this user
    hot_q = select(func.count(Company.id)).where(Company.lead_score >= 60)
    if user.role not in ("admin", "super_admin"):
        hot_q = hot_q.where(Company.assigned_to == user.id)
    overnight["hot_leads_count"] = int((await db.execute(hot_q)).scalar() or 0)

    brief.overnight = overnight

    # ---- Today's priorities ----
    today_start = now_utc.replace(hour=0, minute=0, second=0, microsecond=0)
    tomorrow_start = today_start + timedelta(days=1)

    tasks_today = (await db.execute(
        select(Task, Company.name)
        .join(Company, Task.company_id == Company.id)
        .where(
            Task.user_id == user.id,
            Task.completed == False,
            Task.due_date >= today_start,
            Task.due_date < tomorrow_start,
        )
        .order_by(Task.due_date)
        .limit(8)
    )).all()
    tasks = [
        {
            "id": t.id,
            "description": t.description,
            "company_id": t.company_id,
            "company_name": cname,
            "due_date": t.due_date.isoformat() if t.due_date else None,
        }
        for t, cname in tasks_today
    ]

    # Hot leads for this user, top 5 by score
    hot_q = (
        select(Company)
        .where(Company.lead_score >= 60)
        .order_by(Company.lead_score.desc())
        .limit(5)
    )
    if user.role not in ("admin", "super_admin"):
        hot_q = hot_q.where(Company.assigned_to == user.id)
    hot_rows = (await db.execute(hot_q)).scalars().all()
    hot_leads = [
        {
            "id": c.id, "name": c.name, "lead_score": c.lead_score,
            "lead_score_tier": c.lead_score_tier, "status": c.status,
        }
        for c in hot_rows
    ]

    # Stuck deals: assigned to user, not closed, no update in 14d
    stuck_q = (
        select(Deal, Company.name)
        .join(Company, Deal.company_id == Company.id)
        .where(
            Deal.assigned_to == user.id,
            Deal.stage.notin_(("closed_won", "closed_lost")),
            Deal.updated_at < two_weeks_ago,
        )
        .order_by(Deal.updated_at.asc())
        .limit(5)
    )
    stuck_rows = (await db.execute(stuck_q)).all()
    stuck_deals = [
        {
            "id": d.id, "name": d.name, "stage": d.stage,
            "company_id": d.company_id, "company_name": cname,
            "value": d.value, "days_stuck": (now_utc - _aware(d.updated_at)).days,
        }
        for d, cname in stuck_rows
    ]

    brief.today_priorities = {
        "tasks": tasks,
        "hot_leads": hot_leads,
        "stuck_deals": stuck_deals,
    }

    # ---- Replies awaiting action ----
    replies_q = (
        select(Activity, Company.name)
        .join(Company, Activity.company_id == Company.id)
        .where(
            Activity.activity_type == "email_replied",
            Activity.created_at >= since,
        )
        .order_by(Activity.created_at.desc())
        .limit(8)
    )
    if user.role not in ("admin", "super_admin"):
        replies_q = replies_q.where(Company.assigned_to == user.id)
    replies_rows = (await db.execute(replies_q)).all()
    brief.replies_awaiting = [
        {
            "id": a.id,
            "company_id": a.company_id,
            "company_name": cname,
            "reply_sentiment": a.reply_sentiment,
            "reply_sentiment_summary": a.reply_sentiment_summary,
            "preview": (a.content or "")[:160],
            "created_at": a.created_at.isoformat() if a.created_at else None,
        }
        for a, cname in replies_rows
    ]

    # ---- Weekly stats (this 7d vs prior 7d) ----
    # POST-CUTOVER: count from Activity not GeneratedEmail (see above
    # rationale on overnight sends counter).
    async def _count_user_sends(after: datetime, before: datetime) -> int:
        q = (
            select(func.count(Activity.id))
            .where(
                Activity.activity_type == "email_sent",
                Activity.created_at >= after,
                Activity.created_at < before,
            )
        )
        if user.role not in ("admin", "super_admin"):
            q = q.where(Activity.user_id == user.id)
        return int((await db.execute(q)).scalar() or 0)

    sends_this_week = await _count_user_sends(week_ago, now_utc)
    sends_prior_week = await _count_user_sends(week_ago - timedelta(days=7), week_ago)

    async def _count_user_replies(after: datetime, before: datetime) -> int:
        q = (
            select(func.count(Activity.id))
            .where(
                Activity.activity_type == "email_replied",
                Activity.created_at >= after,
                Activity.created_at < before,
            )
        )
        if user.role not in ("admin", "super_admin"):
            q = q.join(Company, Activity.company_id == Company.id).where(Company.assigned_to == user.id)
        return int((await db.execute(q)).scalar() or 0)

    replies_this_week = await _count_user_replies(week_ago, now_utc)
    replies_prior_week = await _count_user_replies(week_ago - timedelta(days=7), week_ago)

    brief.weekly_stats = {
        "sends_this_week": sends_this_week,
        "sends_prior_week": sends_prior_week,
        "replies_this_week": replies_this_week,
        "replies_prior_week": replies_prior_week,
    }

    # ---- AI insight (one Anthropic call) ----
    brief.ai_insight = await _generate_ai_insight(brief)

    return brief


def _aware(dt: Optional[datetime]) -> datetime:
    if dt is None:
        return datetime.now(timezone.utc)
    return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)


# ============================================================
# AI insight — distill the data into ONE punchy observation
# ============================================================

INSIGHT_SYSTEM = """You are writing the single most valuable observation a sales BDR should know about their pipeline today, based on the JSON data provided.
Output ONE short sentence (under 200 chars). No preamble, no greeting.
Examples of good insights:
  - "Smith Pools opened your email 4× yesterday + visited 3 pages — call them today before they cool off."
  - "3 of 4 replies this week were 'interested' — your follow-up sequence is converting; double the daily send cap."
  - "Phoenix pool builders campaign just ran 12 ticks overnight but enrolled 0 — all targets returned dupes. Time to expand to Tucson."
  - "Sarah Martinez at Backyard Living replied 'send pricing' yesterday and there is no follow-up task on your list."
Pick the angle that matters most. If nothing notable, return an empty string."""


async def _generate_ai_insight(brief: BriefData) -> str:
    if not settings.anthropic_api_key:
        return ""
    payload = {
        "user_first_name": brief.user.get("first_name") or "",
        "overnight": brief.overnight,
        "tasks_today_count": len(brief.today_priorities.get("tasks", [])),
        "hot_leads": brief.today_priorities.get("hot_leads", []),
        "stuck_deals": brief.today_priorities.get("stuck_deals", []),
        "replies_awaiting": brief.replies_awaiting,
        "weekly_stats": brief.weekly_stats,
    }
    try:
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.post(
                "https://api.anthropic.com/v1/messages",
                headers={
                    "x-api-key": settings.anthropic_api_key,
                    "anthropic-version": "2023-06-01",
                    "content-type": "application/json",
                },
                json={
                    "model": "claude-sonnet-4-20250514",
                    "max_tokens": 120,
                    "system": INSIGHT_SYSTEM,
                    "messages": [{"role": "user", "content": json.dumps(payload, default=str)}],
                },
            )
        if r.status_code != 200:
            return ""
        data = r.json()
        text = (data.get("content", [{}])[0] or {}).get("text", "").strip()
        # Meter
        try:
            from app.services.credit_meter import meter_standalone
            await meter_standalone(action_type="ai_summary", action_ref="morning_brief",
                                   raw_cost_override_usd=0.005,
                                   metadata={"user_id": brief.user.get("id")})
        except Exception:
            pass
        return text[:280]
    except Exception as e:
        log.warning(f"AI insight failed for user {brief.user.get('id')}: {e}")
        return ""


# ============================================================
# Render — HTML body
# ============================================================

def _esc(s) -> str:
    if s is None: return ""
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _delta_arrow(now: int, prior: int) -> str:
    if prior == 0:
        return "—" if now == 0 else "🆕"
    pct = round(((now - prior) / max(prior, 1)) * 100)
    if pct >= 10:  return f'<span style="color:#1B5E20">▲ {pct}%</span>'
    if pct <= -10: return f'<span style="color:#c0392b">▼ {abs(pct)}%</span>'
    return f'<span style="color:#888">→ {pct:+d}%</span>'


def render_brief_html(brief: BriefData, public_url: str) -> str:
    name = brief.user.get("first_name") or "there"
    o = brief.overnight
    hot = brief.today_priorities.get("hot_leads", [])
    tasks = brief.today_priorities.get("tasks", [])
    stuck = brief.today_priorities.get("stuck_deals", [])
    replies = brief.replies_awaiting
    s = brief.weekly_stats

    def _hot_row(c):
        tier_color = {"burning": "#b71c1c", "hot": "#bf360c", "warm": "#7a5c00", "cool": "#0d47a1"}.get(c["lead_score_tier"], "#666")
        return f'<tr><td style="padding:6px 8px"><a href="{public_url}/?company_id={c["id"]}" style="color:#1B5E20;text-decoration:none">{_esc(c["name"])}</a></td><td style="padding:6px 8px;text-align:right;color:{tier_color};font-weight:600">{c["lead_score"]} {c["lead_score_tier"]}</td></tr>'

    def _task_row(t):
        return f'<li style="margin-bottom:4px">{_esc(t["description"])} <span style="color:#888;font-size:11px">· {_esc(t["company_name"])}</span></li>'

    def _stuck_row(d):
        return f'<li style="margin-bottom:4px"><strong>{_esc(d["company_name"])}</strong> · {_esc(d["stage"]).replace("_", " ")} · stuck {d["days_stuck"]}d</li>'

    def _reply_row(r):
        sent = r.get("reply_sentiment") or "other"
        sent_color = {"interested": "#1b5e20", "objection": "#bf360c", "out_of_office": "#455a64", "wrong_person": "#6a1b9a", "unsubscribe": "#b71c1c"}.get(sent, "#555")
        return f'<li style="margin-bottom:6px"><strong>{_esc(r["company_name"])}</strong> <span style="color:{sent_color};font-size:11px;font-weight:600;text-transform:uppercase">{sent.replace("_", " ")}</span><br><span style="color:#666;font-size:12px">{_esc(r.get("reply_sentiment_summary") or r.get("preview", ""))[:160]}</span></li>'

    insight_block = (
        f'<div style="background:#fff5f0;border-left:3px solid #FF723F;padding:14px 16px;border-radius:6px;margin:18px 0">'
        f'<div style="font-size:11px;color:#E65100;text-transform:uppercase;letter-spacing:0.4px;font-weight:700;margin-bottom:6px">⚡ One thing to know</div>'
        f'<div style="font-size:14px;color:#333;line-height:1.5">{_esc(brief.ai_insight)}</div></div>'
    ) if brief.ai_insight else ""

    return f"""<!DOCTYPE html>
<html><body style="margin:0;padding:0;background:#f5f7f5;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;color:#1a1a1a">
<div style="max-width:640px;margin:0 auto;padding:20px;background:#f5f7f5">

  <!-- Header -->
  <div style="background:linear-gradient(135deg,#0D3B13,#1B5E20);color:white;border-radius:12px;padding:24px;margin-bottom:16px">
    <div style="font-size:11px;color:rgba(255,255,255,0.7);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px">☀️ Morning Brief</div>
    <h1 style="margin:0;font-size:22px">Good morning, {_esc(name)}</h1>
    <p style="color:rgba(255,255,255,0.8);font-size:13px;margin-top:6px">Here's what happened overnight + what to do today.</p>
  </div>

  {insight_block}

  <!-- Overnight stats -->
  <div style="background:white;border-radius:12px;padding:18px;margin-bottom:14px;box-shadow:0 1px 4px rgba(0,0,0,0.04)">
    <h2 style="font-size:14px;color:#1B5E20;margin:0 0 10px;padding-bottom:6px;border-bottom:1px solid #f0f0f0">While you slept</h2>
    <div style="display:flex;flex-wrap:wrap;gap:10px">
      <div style="flex:1;min-width:120px;background:#f8f9fa;padding:10px;border-radius:6px;text-align:center">
        <div style="font-size:22px;font-weight:700;color:#1b5e20">{o.get("contacts_enrolled_overnight", 0)}</div>
        <div style="font-size:10px;color:#888;text-transform:uppercase">Contacts enrolled</div>
      </div>
      <div style="flex:1;min-width:120px;background:#f8f9fa;padding:10px;border-radius:6px;text-align:center">
        <div style="font-size:22px;font-weight:700">{o.get("sends_overnight", 0)}</div>
        <div style="font-size:10px;color:#888;text-transform:uppercase">Emails sent</div>
      </div>
      <div style="flex:1;min-width:120px;background:#f8f9fa;padding:10px;border-radius:6px;text-align:center">
        <div style="font-size:22px;font-weight:700;color:#FF723F">{o.get("replies_overnight", 0)}</div>
        <div style="font-size:10px;color:#888;text-transform:uppercase">Replies</div>
      </div>
      <div style="flex:1;min-width:120px;background:#f8f9fa;padding:10px;border-radius:6px;text-align:center">
        <div style="font-size:22px;font-weight:700">{o.get("hot_leads_count", 0)}</div>
        <div style="font-size:10px;color:#888;text-transform:uppercase">Hot leads total</div>
      </div>
    </div>
  </div>

  <!-- Today's priorities -->
  <div style="background:white;border-radius:12px;padding:18px;margin-bottom:14px;box-shadow:0 1px 4px rgba(0,0,0,0.04)">
    <h2 style="font-size:14px;color:#1B5E20;margin:0 0 10px;padding-bottom:6px;border-bottom:1px solid #f0f0f0">Today's plan</h2>
    {f'<div style="font-size:12px;color:#888;font-style:italic">No tasks due today and no hot leads — quiet morning ahead.</div>' if not tasks and not hot and not stuck else ''}
    {f'<div style="margin-bottom:12px"><strong style="font-size:12px">Tasks due today ({len(tasks)})</strong><ul style="font-size:13px;color:#444;padding-left:20px;margin:6px 0 0">' + "".join(_task_row(t) for t in tasks) + '</ul></div>' if tasks else ''}
    {f'<div style="margin-bottom:12px"><strong style="font-size:12px">Top hot leads</strong><table style="width:100%;font-size:13px;border-collapse:collapse;margin-top:6px">' + "".join(_hot_row(c) for c in hot) + '</table></div>' if hot else ''}
    {f'<div><strong style="font-size:12px;color:#bf360c">Stuck deals (no update in 14d)</strong><ul style="font-size:13px;color:#444;padding-left:20px;margin:6px 0 0">' + "".join(_stuck_row(d) for d in stuck) + '</ul></div>' if stuck else ''}
  </div>

  {f'''<!-- Replies awaiting action -->
  <div style="background:white;border-radius:12px;padding:18px;margin-bottom:14px;box-shadow:0 1px 4px rgba(0,0,0,0.04)">
    <h2 style="font-size:14px;color:#1B5E20;margin:0 0 10px;padding-bottom:6px;border-bottom:1px solid #f0f0f0">Replies awaiting your action ({len(replies)})</h2>
    <ul style="padding-left:20px;margin:0;list-style:none">
      {"".join(_reply_row(r) for r in replies)}
    </ul>
  </div>''' if replies else ''}

  <!-- Weekly stats -->
  <div style="background:white;border-radius:12px;padding:18px;margin-bottom:14px;box-shadow:0 1px 4px rgba(0,0,0,0.04)">
    <h2 style="font-size:14px;color:#1B5E20;margin:0 0 10px;padding-bottom:6px;border-bottom:1px solid #f0f0f0">This week vs. last</h2>
    <table style="width:100%;font-size:13px;border-collapse:collapse">
      <tr style="border-bottom:1px solid #f5f5f5"><td style="padding:6px 8px">Emails sent</td><td style="padding:6px 8px;text-align:right">{s.get("sends_this_week", 0)} / {s.get("sends_prior_week", 0)} {_delta_arrow(s.get("sends_this_week", 0), s.get("sends_prior_week", 0))}</td></tr>
      <tr><td style="padding:6px 8px">Replies received</td><td style="padding:6px 8px;text-align:right">{s.get("replies_this_week", 0)} / {s.get("replies_prior_week", 0)} {_delta_arrow(s.get("replies_this_week", 0), s.get("replies_prior_week", 0))}</td></tr>
    </table>
  </div>

  <!-- Footer -->
  <div style="text-align:center;color:#888;font-size:11px;margin-top:18px">
    <a href="{public_url}/?page=settings" style="color:#888;text-decoration:underline">Manage brief settings</a>
    &nbsp;·&nbsp; <a href="{public_url}" style="color:#888;text-decoration:underline">Open Prospector</a>
    <p style="margin:8px 0 0;color:#aaa">Backyard Marketing Pros · Las Vegas, NV</p>
  </div>

</div>
</body></html>"""


# ============================================================
# Send — wraps everything together
# ============================================================

def _brief_subject(brief: BriefData) -> str:
    o = brief.overnight or {}
    if o.get("replies_overnight"):
        n = o["replies_overnight"]
        word = "reply" if n == 1 else "replies"
        return f"☀️ {n} {word} to act on this morning"
    if o.get("contacts_enrolled_overnight"):
        return f"☀️ {o['contacts_enrolled_overnight']} contacts enrolled overnight"
    return "Your morning brief"


def _html_to_text(html: str) -> str:
    """Cheap plaintext alternative — Gmail / Outlook prefer multipart
    messages and downgrade us to spam more readily without one. Strips
    tags + collapses whitespace; doesn't try to be pretty."""
    import re as _re
    txt = _re.sub(r"<style[^>]*>.*?</style>", "", html, flags=_re.S | _re.I)
    txt = _re.sub(r"<script[^>]*>.*?</script>", "", txt, flags=_re.S | _re.I)
    txt = _re.sub(r"<[^>]+>", " ", txt)
    txt = _re.sub(r"&nbsp;", " ", txt)
    txt = _re.sub(r"&amp;", "&", txt)
    txt = _re.sub(r"&lt;", "<", txt)
    txt = _re.sub(r"&gt;", ">", txt)
    txt = _re.sub(r"&#x[0-9A-Fa-f]+;|&#[0-9]+;", "", txt)
    txt = _re.sub(r"\s+", " ", txt).strip()
    return txt[:3500]


async def send_brief(db: AsyncSession, user: User) -> bool:
    """Build + render + send + stamp. Returns True if Resend accepted.

    Deliverability hardening (matches the normal outbound-email path):
      - From-line uses the user's first-name local-part instead of
        'noreply@' — Gmail Promotions filters love 'noreply'
      - List-Unsubscribe + List-Unsubscribe-Post headers signal
        legitimate transactional / opted-in mail
      - Plain-text alternative for clients that downgrade or score
        HTML-only as promotional
      - X-Entity-Ref-ID + custom tags for Resend logs filtering
    """
    if not settings.resend_api_key or not user.email:
        log.warning(f"send_brief skipped for user {user.id}: missing api_key or email")
        return False
    public_url = settings.public_url.rstrip("/")
    brief = await build_brief(db, user)
    html = render_brief_html(brief, public_url)
    text_alt = _html_to_text(html)

    subject = _brief_subject(brief)

    # First-name@send_domain looks like a real person, not a robot.
    # Falls back to 'team' if the user has no first name set.
    fn = (user.first_name or "").strip().lower()
    if not fn and user.full_name:
        fn = user.full_name.strip().split()[0].lower()
    fn = fn or "team"
    from_local = fn.replace(" ", "")
    from_address = f"{user.first_name or 'BMP'} from BMP <{from_local}@{settings.send_domain}>"

    # List-Unsubscribe — surfaces native Gmail/Outlook unsubscribe button
    # AND tells filters this is well-behaved automated mail. Points at a
    # generic settings page; the brief itself is opt-out via Settings.
    unsub_url = f"{public_url}/?page=settings"

    payload = {
        "from": from_address,
        "to": [user.email],
        "reply_to": user.email,  # they hit Reply, it goes to themselves; safe
        "subject": subject,
        "html": html,
        "text": text_alt,
        "headers": {
            "List-Unsubscribe": f"<{unsub_url}>",
            "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
            "X-Entity-Ref-ID": f"morning-brief-{user.id}-{datetime.now(timezone.utc).date().isoformat()}",
        },
        "tags": [
            {"name": "kind", "value": "morning_brief"},
            {"name": "user_id", "value": str(user.id)},
        ],
    }
    try:
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.post(
                "https://api.resend.com/emails",
                headers={
                    "Authorization": f"Bearer {settings.resend_api_key}",
                    "Content-Type": "application/json",
                },
                json=payload,
            )
        if r.status_code in (200, 201):
            log.info(f"morning brief sent → user {user.id} ({user.email})")
            user.last_brief_sent_at = datetime.now(timezone.utc)
            await db.commit()
            try:
                from app.services.credit_meter import meter, make_idem_key
                await meter(
                    db, action_type="email_send",
                    idempotency_key=make_idem_key("morning_brief", user.id, datetime.now(timezone.utc).date().isoformat()),
                    user_id=user.id,
                    action_ref=f"morning_brief:{user.id}",
                )
                await db.commit()
            except Exception:
                pass
            return True
        log.warning(f"Resend rejected morning brief for user {user.id}: {r.status_code} — {r.text[:300]}")
        return False
    except Exception as e:
        log.warning(f"send_brief failed for user {user.id}: {e}")
        return False


# ============================================================
# Cron tick — called every 15 min from main.py lifespan
# ============================================================

async def run_morning_brief_tick(db: AsyncSession) -> int:
    """Find users whose local time has just crossed brief_hour and we
    haven't sent yet today. Returns count of briefs sent this tick."""
    now_utc = datetime.now(timezone.utc)
    candidates = (await db.execute(
        select(User).where(
            User.is_active == True,
            User.brief_enabled == True,
            User.email != "",
        )
    )).scalars().all()

    sent = 0
    for user in candidates:
        try:
            tz = ZoneInfo(user.timezone or "America/Phoenix")
        except Exception:
            tz = ZoneInfo("America/Phoenix")
        local_now = now_utc.astimezone(tz)
        # Only fire when local hour matches brief_hour. The tick runs
        # every 15 min, so this triggers within a 15-min window once a day.
        if local_now.hour != user.brief_hour:
            continue
        # Has a brief already gone out today (in user's local tz)?
        last = user.last_brief_sent_at
        if last:
            last_local = (last if last.tzinfo else last.replace(tzinfo=timezone.utc)).astimezone(tz)
            if last_local.date() == local_now.date():
                continue
        ok = await send_brief(db, user)
        if ok:
            sent += 1
    return sent
